"""create initial household tables

Revision ID: 045904046832
Revises:
Create Date: 2026-09-20 19:50:06.770331

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "045904046832"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliveries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("carrier", sa.String(length=100), nullable=True),
        sa.Column("tracking_reference", sa.String(length=150), nullable=True),
        sa.Column(
            "status",
            sa.Enum("expected", "delivered", "collected", name="deliverystatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("expected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_location", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_deliveries_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_deliveries_tracking_reference"), ["tracking_reference"], unique=False
        )

    op.create_table(
        "household_presence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("occupant_name", sa.String(length=150), nullable=False),
        sa.Column(
            "status",
            sa.Enum("home", "away", "sleeping", name="presencestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("household_presence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_household_presence_occupant_name"), ["occupant_name"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_household_presence_status"), ["status"], unique=False)

    op.create_table(
        "household_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "completed", "cancelled", name="taskstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "critical", name="taskpriority", native_enum=False),
            nullable=False,
        ),
        sa.Column("requires_confirmation", sa.Boolean(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("household_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_household_tasks_priority"), ["priority"], unique=False)
        batch_op.create_index(batch_op.f("ix_household_tasks_status"), ["status"], unique=False)

    op.create_table(
        "expected_visitors",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("purpose", sa.String(length=255), nullable=False),
        sa.Column("expected_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "expected",
                "arrived",
                "departed",
                "missed",
                "cancelled",
                name="visitorstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("related_task_id", sa.String(length=36), nullable=True),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("departed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["related_task_id"], ["household_tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("expected_visitors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_expected_visitors_expected_start"), ["expected_start"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_expected_visitors_status"), ["status"], unique=False)

    op.create_table(
        "home_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "visitor_detected",
                "package_delivered",
                "motion_detected",
                "doorbell_pressed",
                "door_opened",
                "system",
                name="eventtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("ring_simulator", "manual", "system", name="eventsource", native_enum=False),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=100), nullable=False),
        sa.Column("summary", sa.String(length=255), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("is_simulated", sa.Boolean(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("related_visitor_id", sa.String(length=36), nullable=True),
        sa.Column("related_task_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 100)",
            name="ck_home_events_confidence",
        ),
        sa.ForeignKeyConstraint(["related_task_id"], ["household_tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["related_visitor_id"], ["expected_visitors.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("home_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_home_events_event_type"), ["event_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_home_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_home_events_source"), ["source"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("home_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_home_events_source"))
        batch_op.drop_index(batch_op.f("ix_home_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_home_events_event_type"))

    op.drop_table("home_events")
    with op.batch_alter_table("expected_visitors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_expected_visitors_status"))
        batch_op.drop_index(batch_op.f("ix_expected_visitors_expected_start"))

    op.drop_table("expected_visitors")
    with op.batch_alter_table("household_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_household_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_household_tasks_priority"))

    op.drop_table("household_tasks")
    with op.batch_alter_table("household_presence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_household_presence_status"))
        batch_op.drop_index(batch_op.f("ix_household_presence_occupant_name"))

    op.drop_table("household_presence")
    with op.batch_alter_table("deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deliveries_tracking_reference"))
        batch_op.drop_index(batch_op.f("ix_deliveries_status"))

    op.drop_table("deliveries")
    # ### end Alembic commands ###
